# Generated by Django 3.2.7 on 2021-09-22 03:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='contributers',
            field=models.ManyToManyField(related_name='contributers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=False, max_length=15), default=None, size=None),
        ),
    ]
