# Generated by Django 3.2.7 on 2021-10-20 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_auto_20211018_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_api.user'),
            preserve_default=False,
        ),
    ]
