# Generated by Django 3.2.7 on 2021-10-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_labels_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='user',
            new_name='user_id',
        ),
    ]
